# docker-compose.yml
version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  api-gateway:
    build: ./api-gateway
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - keycloak

  user-service:
    build: ./user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - keycloak-db

  problem-service:
    build: ./problem-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - keycloak-db

  submission-service:
    build: ./submission-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - keycloak-db

  frontend:
    build: ./frontend
    ports:
      - "8082:8082"
    depends_on:
      - api-gateway