# api-gateway/src/main/resources/application.yml
server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        - id: problem-service
          uri: lb://problem-service
          predicates:
            - Path=/api/problems/**
          filters:
            - AuthenticationFilter

        - id: submission-service
          uri: lb://submission-service
          predicates:
            - Path=/api/submissions/**
          filters:
            - AuthenticationFilter

        - id: frontend-public
          uri: lb://frontend
          predicates:
            - Path=/public/**, /css/**, /js/**, /images/**

        - id: frontend-secure
          uri: lb://frontend
          predicates:
            - Path=/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka