server:
  port: 8989

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: problem-service
          uri: lb://PROBLEM-SERVICE
          predicates:
            - Path=/api/problem**
        - id: submission-service
          uri: lb://SUBMISSION-SERVICE
          predicates:
            - Path=/api/submissions**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://192.168.1.175:8080/realms/code-competition