server:
  port: 8095

spring:
  application:
    name: submission.service
  datasource:
    url: jdbc:postgresql://192.168.1.175:5432/submission-db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: da065a58b41746b01e6af69d14b0fe999b0b7b1e1a080bc6b6dca40013647e5f
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 1209600000

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
